services:
  influxdb:
    image: influxdb:3.5.0-core
    container_name: influxdb
    user: root
    ports:
      - 8181:8181
    volumes:
      - influx-data:/var/lib/influxdb3/data
      - influx-plugins:/var/lib/influxdb3/plugins
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins

  influxdb-explorer:
    image: influxdata/influxdb3-ui:1.3.0
    container_name: influxdb-explorer
    user: root
    restart: unless-stopped
    ports:
      - 8888:80
      - 8889:8888
    environment:
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY:-changeme123456789012345678901234}
      DATABASE_URL: /db/sqlite.db
    volumes:
      - influx-explorer-db:/db:rw
      - influx-explorer-config:/app-root/config:rw
    command: ["--mode=admin"]

  grafana:
    image: grafana/grafana-enterprise:12.3.0-18209090404-boringcrypto
    container_name: grafana
    restart: unless-stopped
    ports:
      - '33000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
    influx-data:
    influx-plugins:
    influx-explorer-db:
    influx-explorer-config:
    grafana-data: