[package]
name = "arksync-actuator"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "arksync-actuator"
path = "src/bin/arksync-actuator.rs"

[features]
default = []
esp-gpio = []
linux-gpio = ["dep:gpiocdev"]

[dependencies]
arksync-bus.workspace = true
gpiocdev = { workspace = true, optional = true }
log.workspace = true
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }

[lints]
workspace = true
