name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  linting:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev
          version: 1.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - run: cargo clippy --workspace --tests --all-features -- -D warnings

  # testing:
  #   name: cargo nextest
  #   runs-on: ubuntu-latest
  #   env:
  #     CARGO_TERM_COLOR: always
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: taiki-e/install-action@v2
  #       with:
  #         tool: nextest
  #     - run: cargo nextest run --all-features --profile ci