name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  rust:
    name: cargo clippy + nextest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libudev-dev
          version: 1.0

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - run: cargo clippy --workspace --tests --all-features -- -D warnings
      - run: cargo nextest run --workspace --all-features --profile ci
